DROP TABLE user IF EXISTS;
CREATE TABLE user(
   id BIGINT GENERATED BY DEFAULT AS identity,
   username varchar(40),
   name varchar(20),
   age int(3),
   balance decimal(10,2),
   primary key(id)
);